# Generated by Django 2.2.6 on 2019-10-15 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Título')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('debug', 'Debug'), ('error', 'Error'), ('warning', 'Warning'), ('information', 'Info')], max_length=20, verbose_name='Tipo')),
                ('environment', models.CharField(choices=[('development', 'Dev'), ('homologation', 'Homologação'), ('production', 'Produção')], max_length=20, verbose_name='Ambiente')),
                ('address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv4_address], verbose_name='Endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('events', models.IntegerField(verbose_name='Eventos')),
                ('filed', models.BooleanField(default=False, verbose_name='Arquivado')),
                ('excluded', models.BooleanField(default=False, verbose_name='Excluído')),
            ],
        ),
    ]
