# Generated by Django 2.2.6 on 2019-10-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_auto_20191019_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='excluded',
        ),
    ]
